Create BaseYii stub
Practically/PsalmPluginYii2 pull request #6
Opened 2021-10-02 14:42 UTC by WinterSilence

2021-10-04 13:42 UTC, AdeAttwood requested changes
This is cool, thanks for the contribution.

If we can get some tests on this, that will be perfect. Maybe a test with it failing when you pass an integer to the function?

I don't have the actions set up on PRs, so I will get that fixed, then if we can get this rebased, so we can get all the tests checked. The only thing I can see an issue with is the commit message. If you fancy it you can sort that out, if not I will sort that when merging.

2021-10-04 13:42 UTC, AdeAttwood commented on stubs/BaseYii.phpstub
> +<?php
```suggestion
<?php
/**
 * Copyright 2021 Practically.io All rights reserved
 *
 * Use of this source is governed by a BSD-style
 * licence that can be found in the LICENCE file or at
 * https://www.practically.io/copyright/
 */
declare(strict_types=1);
```

Can we get the file header in here, please?

https://github.com/Practically/PsalmPluginYii2/blob/1.x/stubs/ActiveQuery.phpstub#L1-L9

2021-10-04 17:46 UTC, WinterSilence commented
@AdeAttwood I take that code from package https://github.com/proget-hq/phpstan-yii2

2021-10-04 18:41 UTC, AdeAttwood commented
This code is good as is, just needs some tests. @WinterSilence would you like me to finish this PR off and push the changes to `WinterSilence/PsalmPluginYii2`

2021-10-04 18:47 UTC, WinterSilence commented
@AdeAttwood  don't understand you

2021-10-04 18:51 UTC, WinterSilence commented
@AdeAttwood don't know how test stubs, but if is work fine in phpstan plugin it's must work fine in psalm plugin too

2021-10-05 07:56 UTC, AdeAttwood commented
> but if is work fine in phpstan plugin it's must work fine in psalm plugin too

Unfortunately to often this is not the case. I will get some test done and get this merged in the next couple of days.

2021-10-06 12:32 UTC, WinterSilence commented
@AdeAttwood merged with stub generated by `psalm --generate-stubs`

2021-12-13 16:54 UTC, AdeAttwood commented
@WinterSilence thanks for this, sorry for the delay it has been put in with #9 with the tests. If you want to see how the tests are done for the stubs, then you can see them [here](https://github.com/Practically/PsalmPluginYii2/pull/9/commits/21c491e2f5f829c6aba210b6d3c9d83b508207a3)

2021-12-13 16:54 UTC, closed without merging